---
- hosts: all

  tasks:
    - name: Updating and upgrading package list
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Installing ZSH, Exa, and Neofetch
      become: true
      apt:
        pkg:
          - zsh
          - exa
          - neofetch

    - name: Adds default id_rsa key
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
